-- Alteramos la session para poder crear un nuevo usuario
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
-- CREATE USER "usuario" IDENTIFIED BY "password" (Yo pongo HR en ambos por comodidad)
CREATE USER HR IDENTIFIED BY HR;
-- GRANT CREATE SESSION TO "usuario";
GRANT CREATE SESSION TO HR;
-- GRANT CREATE TABLE TO "usuario";
GRANT CREATE TABLE TO HR;
-- GRANT CREATE PROCEDURE TO "usuario";
GRANT CREATE PROCEDURE TO HR;
-- GRANT UNLIMITED TABLESPACE TO "usuario";
GRANT UNLIMITED TABLESPACE TO HR;
